//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRecomendationDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_isbn { get; set; }
        public string title { get; set; }
        public int book_edition { get; set; }
        public int author_id { get; set; }
    }
}
